image: archlinux
packages:
  - meson
  - wayland
  - scdoc
  - libvarlink
sources:
  - https://git.sr.ht/~emersion/kanshi
tasks:
  - setup: |
      cd kanshi
      meson setup build/ -Dauto_features=enabled
  - build: |
      cd kanshi
      ninja -C build/
  - build-features-disabled: |
      cd kanshi
      meson setup build/ --reconfigure -Dauto_features=disabled
      ninja -C build/
