kanshictl(1)

# NAME

kanshictl - control the kanshi daemon remotely

# SYNOPSIS

*kanshictl* [options...] [command]

# OPTIONS

*-h, --help*
	Show help message and quit.

# COMMANDS

*reload*
	Reload the config file.

*switch* <profile>
	Switch to a different profile.

# AUTHORS

Maintained by Simon Ser <contact@emersion.fr>, who is assisted by other
open-source contributors. For more information about kanshi development, see
https://git.sr.ht/~emersion/kanshi.

# SEE ALSO

*kanshi*(1)
